# Generated by Django 3.1.4 on 2020-12-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=40)),
                ('age', models.IntegerField()),
                ('dateofbirth', models.DateField()),
                ('date_of_employment', models.DateField(default='2017-04-09')),
                ('position', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=40)),
                ('age', models.IntegerField()),
                ('date_of_birth', models.DateField(help_text='format: yy-mm-dd (eg. 2020-12-14)')),
                ('date_of_employment', models.DateField(default='2017-04-09', help_text='format: yy-mm-dd (eg. 2020-12-14)')),
                ('position', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('supervisors', models.ManyToManyField(blank=True, null=True, related_name='employees', to='base.Supervisor', verbose_name='supervisors')),
            ],
        ),
    ]
