# Generated by Django 3.1.4 on 2020-12-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=40)),
                ('age', models.IntegerField()),
                ('dateofbirth', models.DateField()),
                ('position', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=40)),
                ('age', models.IntegerField()),
                ('dateofbirth', models.DateField()),
                ('position', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('supervisors', models.ManyToManyField(related_name='employees', to='base.Supervisor', verbose_name='supervisors')),
            ],
        ),
    ]
