# Generated by Django 3.1.4 on 2020-12-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='dateofbirth',
            new_name='date_of_birth',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.AlterField(
            model_name='employee',
            name='supervisors',
            field=models.ManyToManyField(blank=True, null=True, related_name='employees', to='base.Supervisor', verbose_name='supervisors'),
        ),
    ]
