# Generated by Django 3.0.6 on 2020-12-18 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20201217_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date_of_employment',
            field=models.DateField(default='2017-04-09', help_text='format: yy-mm-dd (eg. 2020-12-14)'),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='date_of_employment',
            field=models.DateField(default='2017-04-09'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(help_text='format: yy-mm-dd (eg. 2020-12-14)'),
        ),
    ]
